server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
  http2:
    enabled: true
  servlet:
    session:
      cookie:
        name: KSESSION
spring:
  application:
    name: icon-efiling
  profiles:
    active: dev
  thymeleaf:
    mode: LEGACYHTML5
  servlet:
    multipart:
      enabled: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
logging:
  config: classpath:logback-spring.xml

security:
  oauth2:
    client:
      client-id: mobile
      client-secret: 1234567
      user-authorization-uri: http://localhost:9191/oauth/authorize
      access-token-uri: http://localhost:9191/oauth/token
      auto-approve-scopes: '.*'
    resource:
      token-info-uri: http://localhost:9191/oauth/check_token

app:
  authendpoint: http://localhost:9191
  logouturl: /exit